version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/aiops
    binary: aiops
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/voltic-software/aiops/internal/config.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "aiops_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: voltic-software
    name: aiops
  draft: false
  prerelease: auto
